name: Update

on: 
  release:
    types: [published]
  push:
    tags:
    - 'v*'
  branches: 
    - main
  schedule:
    - cron: "12 */3 * * *"
  watch:
    types: [started]
   
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
    - name: check update
      env: 
        EMAIL: ${{ secrets.EMAIL }}
        USERNAME: ${{ secrets.USERNAME }}
        GH_REF: ${{ secrets.GH_REF }}
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
      run: |
        cd homebrew-xray
        git config --global user.name $USERNAME
        git config --global user.email $EMAIL
        chmod +x checker.sh
        ./checker
